### ISSUE TITLE
We need a option to disable jsLint

### ISSUE THREAD

**Issue by gustahrodrigues** [grommet/grommet-toolbox#23]
As we have an option to disable the scsslint, it would be useful to have an option to disable jsLint also. At least the build should be completed, even if there is a jsList error.

I'm facing some instability issue (that I'm still trying to figure out what's happening), but until I fixed it, I could not proceed with my develop.

**Comment by alansouzati** [comment]
Fair statement, we are planning to deprecate scssLint option. We had that in the past because of the ruby dependency. Now that this is a node-only project. I'm in favor of removing scssLint.

I'm afraid adding these options will lead to people adding that and not removing it, which for me, defeats the purpose of this tool.

I'm going to close this issue for now. Let's work on fixing the instability issue with gulp-cache.

I've created an issue to deprecate scssLint: https://github.com/grommet/grommet-toolbox/issues/27
