### ISSUE TITLE
Any option to remove comments in compressed index.js after run 'gulp dist'?

### ISSUE THREAD

**Issue by buxiaoliang** [grommet/grommet-toolbox#45]
Hi experts,

we want to remove comments in compressed index.js after run 'gulp dist'. 

Then I didn't find an option we can input in webpack.dist.config.js.

Only can do is change it codes as or set skipMinify as 'true' and then compress it by ourselves.

if (!argv.skipMinify) {
  config.plugins.push(new _webpack2.default.optimize.UglifyJsPlugin({
    compress: {
      warnings: false
    },
	**output: {
      comments: false
  },**
  }));
}

Here, my question is that, could give an option to user that make it easy set comments as 'false' to close comment output?

Thanks,

Robert

**Comment by tracybarmore** [comment]
Thanks for the issue. We are looking in to this.

**Comment by buxiaoliang** [comment]
Thanks for your support


Robert






At 2017-01-05 03:12:17, "tracybarmore" <notifications@github.com> wrote:


Thanks for the issue. We are looking in to this.

**Comment by alansouzati** [comment]
right now this is not possible in the toolbox. The configuration to remove comments should be like follows:

```
new webpack.optimize.UglifyJsPlugin({
      compress: {
        screw_ie8: true,
        warnings: false
      },
      mangle: {
        screw_ie8: true
      },
      output: {
        comments: false,
        screw_ie8: true
      }
    })
```

But this config is hidden in the toolbox and not exposed to the callers, unfortunately. 

Because of these limitations we are deprecating the toolbox as we released the new CLI with development environment capabilities. Check this video out where we detail this process:

https://vimeo.com/199912095

The new CLI  already adds the `comments: false` as part of the webpack config.
